num_examples = 1
rollouts_per_example = 1
max_concurrent = 1
save_results = true
state_columns = ["dynamic"]

[[eval]]
env_id = "neural-forager"

[eval.env_args.config.taskset.dynamic]
seeds = [7]
neural_seeds = [31]
